### ISSUE TITLE
X/TwitterやYoutubeの埋め込み

### ISSUE THREAD

**Issue by cm-sagojo** [cm-devcamp/devcamp_app1_wada#1]
- コーポレートサイトをSNSと連動させるべく、公式アカウントの埋め込みを追加します。
    - X/Twitter公式アカウント: クラスメソッド（@classmethod）さん / X https://x.com/classmethod
    - Youtube公式アカウント: クラスメソッド - YouTube https://www.youtube.com/@classmethod-yt

**Comment by sasuke0339** [comment]
@cm-sagojo 
公式X および YouTube のリンク埋め込みについて質問させてください。

- 公式X は最新ツイートからスクロールできるようにする形でよろしいでしょうか。
- YouTube に関して、具体的にどの動画を埋め込みたいなどございますでしょうか。

**Comment by cm-sagojo** [comment]
@sasuke0339 
ご確認ありがとうございます。
公式X の表示についてはご提案いただいた内容で問題ございません。
YouTube に関しては表示する動画の要望はありません。
よろしくお願いします。

**Comment by sasuke0339** [comment]
@cm-sagojo 
ご確認いただきありがとうございます。
かしこまりました、プルリクエスト済みですのでお手隙の際にご確認よろしくお願いいたします。

**Comment by cm-sagojo** [comment]
#4 にて対応いただいたのでクローズします
