### ISSUE TITLE
Google Analyticsの設置

### ISSUE THREAD

**Issue by cm-sagojo** [cm-devcamp/devcamp_app1_wada#3]
- コーポレートサイトのアクセス解析を取り入れることになりました。つきましては、以下の説明に従いGoogle Analyticsのタグを埋め込んでください。
    
    ```jsx
    Google タグの設定方法を選択
    手動でインストールする おすすめ
    以下は、このアカウントの Google タグです。このタグをコピーして、ウェブサイトのすべてのページのコード（<head> 要素の直後）に貼り付けます。各ページに複数の Google タグを実装することはできません。
    ----
    <!-- Google tag (gtag.js) -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-XXXXXXXX"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());
    
      gtag('config', 'G-XXXXXXXXX');
    </script>
    ```

**Comment by sasuke0339** [comment]
@cm-sagojo 
GoogleAnalytics を設定するために、業種およびビジネス規模、目標をご提示いただけますと幸いです。
以下、GoogleAnalytics 設定時の目標項目です。

- **見込み顧客の発掘**
- **オンライン販売の促進**
- **ブランド認知度の向上**
- **ユーザー行動の調査**
- **ベースライン レポートの取得**

**Comment by cm-sagojo** [comment]
@sasuke0339 
ご確認ありがとうございます。
業種およびビジネス規模、目標は「Devcamp Products」におけるものでよかったでしょうか？
必要であれば上長に確認しますが、本作業においてこの情報がなぜ必要になるかもう少し詳しく説明いただけますでしょうか。

**Comment by sasuke0339** [comment]
@cm-sagojo 
ご確認いただきありがとうございます。
「G-XXXXXXXX」の ID を取得するために、こちらで GoogleAnalytics の登録を進めていく中で問われたためお聞きしました。
ID は未設定のままで良かったのでしょうか。

**Comment by cm-sagojo** [comment]
@sasuke0339 
なるほど、ありがとうございます。理解できました。
そちらについては既にこちらで用意済みですので以下を適用願います。
G-M3TWKDE87B

**Comment by sasuke0339** [comment]
@cm-sagojo 
ご確認いただきありがとうございます。
ご提供いただいた ID を記入の上、プルリクエストいたしました。お手隙の際にご確認いただけますと幸いです。

**Comment by cm-sagojo** [comment]
#6 にて対応いただいたのでクローズします
